### ISSUE TITLE
0x research

### ISSUE THREAD

**Issue by AlinaYozh** [yozh-io/1inch-widget#220]
https://www.0x.org/
What is 0x, how to use it and how we can add it to our widget?

**Comment by trandobulo** [comment]
[Ссылка на таблицу с информацией](https://docs.google.com/spreadsheets/d/1hMpEid92lLhudYGMWixFdn0mfMq4uXHkbq1-xock_hM/edit?usp=sharing)

**Comment by setrix422** [comment]
[Table with updates](https://docs.google.com/spreadsheets/d/16KYsnQq5ODQA7UIuQkDJp3M7qJkEavE9meoCF3p8IEs/edit#gid=0)
