### ISSUE TITLE
Update 1inch api to v5

### ISSUE THREAD

**Issue by AlinaYozh** [yozh-io/1inch-widget#303]
1) Update api repo to v5;
2) update version of published package in package.json to 3.0.0;
3) Update version of api on ui
4) Cherry-pick 🍒 to uniswap branch;

https://github.com/yozh-io/1inch-widget-api-client

**Comment by heimlee** [comment]
For step 1 we can use following command:
`rm -rf client/networks/${network} && npx openapi-generator-cli generate -i ${api-url} -g typescript-fetch -o client/network/${network} -c config.json && cd client/network/${network} && npm i && npm run build`

**Comment by AlinaYozh** [comment]
${network} is ethereum and polygon and another. Look here: https://github.com/yozh-io/1inch-widget-api-client/tree/main/client/networks

Example:
```rm -rf client/networks/ethereum && openapi-generator-cli generate -i https://api.1inch.io/swagger/ethereum-json -g typescript-fetch -o client/networks/ethereum && cd client/networks/ethereum && npm i && npm build```
