### ISSUE TITLE
Routes on Joe Router

### ISSUE THREAD

**Issue by AlinaYozh** [yozh-io/1inch-widget#304]
https://docs.traderjoexyz.com/SDK/trade

1. Come up with generating routs in [JoeRepo](https://github.com/traderjoe-xyz/joe-sdk-v2/blob/fe803e1da037dc19c716c746b8292e27d82b75aa/src/v2entities/route.ts);

~~2. Implement a function to get all routes;
3. Use this function to get routes;
4. Create a common structure to show routes on "Routes" modal window.~~

**Comment by heimlee** [comment]
Comparison of using Trader Joe SDK (SDK) and Joe Router contract (Contract) solely in routes:

1. We can choose the most profitable ways of swap by using SKD. It is possible to create swap pairs of different tokens and choose the best trade from them by using special methods. We can get all necessary information from this trade for both routes and transactions.
Several contracts and classes within SDK are used for all above mentioned features, including Pair, Route, etc.

2. If Contract is used exclusively, options to swap with some "hops" from different tokens (except for WAVAX token, when the swap method is token-to-token) and to choose the best path are not available.
It is possible to show the direct path but without display of token amount and fees for such a swap on "hops" (for example, when there is an interim tx for WAVAX token).
Such information cannot be obtained from joe-core contracts. Therefore if we try to implement desired amount of features manually based solely on the Contract, major part of the achived result will duplicate functionality of SDK.
